name: stackoverflow
description: A StackOverflow project made with Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_cubit: ^0.1.1
  equatable: ^1.2.0
  dio: ^3.0.9
  data_connection_checker: ^0.3.4
  get_it: ^4.0.2
  hive: ^1.3.0
  hive_flutter: null
  shimmer: ^1.1.1
  flutter_html: ^1.0.0
  flutter_staggered_grid_view: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/i18n/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
flutter_intl:
  enabled: true
